"""
agents/skill_teacher.py
Self-learning system. Can write new Python skill plugins at runtime,
verify them, save them, and hot-load without restart.
"""

import os
import re
import ast
import importlib.util
import logging
from typing import Optional

logger = logging.getLogger("Makima.SkillTeacher")

SKILLS_DIR = "learned_skills"

# Built-in capabilities — no need to learn these
BUILTIN_ABILITIES = [
    "volume", "spotify", "focus mode", "macros", "email", "whatsapp",
    "app launcher", "window manager", "screenshot", "weather", "battery",
    "time", "reminders", "calendar", "system", "browser", "media",
    "search", "cpu", "ram", "lock", "minimize", "maximize",
]


class SkillTeacher:
    """Teaches Makima new skills by generating and loading Python plugins."""

    def __init__(self, ai, router):
        self.ai = ai
        self.router = router
        self.learned_skills: dict[str, dict] = {}  # name → {module, keywords, func}
        os.makedirs(SKILLS_DIR, exist_ok=True)
        self._load_existing_skills()

    # ─── Skill Detection ──────────────────────────────────────────────────────

    def _is_builtin(self, task: str) -> bool:
        task_lower = task.lower()
        return any(ability in task_lower for ability in BUILTIN_ABILITIES)

    def _fuzzy_match_learned(self, user_input: str) -> Optional[str]:
        """Check if input roughly matches a learned skill name."""
        input_words = set(user_input.lower().split())
        best_name = None
        best_overlap = 0
        for skill_name, skill in self.learned_skills.items():
            keywords = set(skill.get("keywords", skill_name.split("_")))
            overlap = len(input_words & keywords)
            if overlap > best_overlap:
                best_overlap = overlap
                best_name = skill_name
        if best_overlap >= 2:
            return best_name
        return None

    # ─── Code Generation ──────────────────────────────────────────────────────

    SKILL_TEMPLATE = '''"""
Learned skill: {task}
Auto-generated by Makima SkillTeacher.
"""

SKILL_NAME = "{name}"
SKILL_KEYWORDS = {keywords}


def run(args: str = "") -> str:
    """Execute the skill. Return a string response for Makima to speak."""
    {code}
'''

    def _generate_skill_code(self, task: str, name: str, keywords: list[str]) -> str:
        prompt = (
            f"Write a Python function body for a Makima assistant skill.\n"
            f"Task: {task}\n\n"
            f"Rules:\n"
            f"1. Write ONLY the function body (no def line, no class).\n"
            f"2. Use standard library or common packages (os, subprocess, psutil, pyautogui, requests).\n"
            f"3. Return a string that Makima will speak aloud.\n"
            f"4. Handle exceptions gracefully and return an error string if something fails.\n"
            f"5. Keep it short — under 30 lines.\n"
            f"6. Do NOT include markdown code fences.\n\n"
            f"Function body only:"
        )
        raw, _ = self.ai.chat(prompt)   # ai.chat() returns (reply, emotion)
        # Strip markdown fences if the model includes them
        raw = re.sub(r"```python\s*", "", raw)
        raw = re.sub(r"```\s*", "", raw)
        # Indent all lines for the function body
        indented = "\n    ".join(raw.strip().splitlines())
        return indented

    def _verify_code(self, code_str: str) -> tuple[bool, str]:
        """Check that the code is valid Python."""
        try:
            ast.parse(code_str)
            return True, ""
        except SyntaxError as e:
            return False, str(e)

    # ─── Teaching ─────────────────────────────────────────────────────────────

    def teach(self, task: str, max_retries: int = 2) -> str:
        """Learn a new skill for the given task."""
        if self._is_builtin(task):
            return f"I already know how to do that! Just tell me to do it directly."

        # Normalize skill name
        name = re.sub(r"[^a-z0-9]+", "_", task.lower().strip())[:40]
        if name in self.learned_skills:
            return f"I already learned how to {task}."

        keywords = list(set(task.lower().split()))
        logger.info(f"📚 Learning skill: {name}")

        for attempt in range(max_retries + 1):
            try:
                body = self._generate_skill_code(task, name, keywords)
                file_content = self.SKILL_TEMPLATE.format(
                    task=task, name=name,
                    keywords=repr(keywords),
                    code=body,
                )
                valid, err = self._verify_code(file_content)
                if valid:
                    path = os.path.join(SKILLS_DIR, f"{name}.py")
                    with open(path, "w", encoding="utf-8") as f:
                        f.write(file_content)
                    self._hot_load(name, path, keywords)
                    logger.info(f"✅ Skill '{name}' learned and saved.")
                    return f"Got it! I've learned how to {task}. You can ask me to do it anytime."
                else:
                    logger.warning(f"Attempt {attempt+1}: Syntax error in generated code: {err}")
                    if attempt < max_retries:
                        # Ask AI to self-correct
                        task = f"Fix this Python code error ({err}) in: {task}"
            except Exception as e:
                logger.error(f"Skill generation failed: {e}")

        return f"I tried to learn '{task}' but couldn't generate valid code. Try rephrasing."

    # ─── Hot Loading ──────────────────────────────────────────────────────────

    def _hot_load(self, name: str, path: str, keywords: list[str]):
        """Dynamically load a skill module without restarting."""
        spec = importlib.util.spec_from_file_location(name, path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        self.learned_skills[name] = {
            "module": module,
            "keywords": set(keywords),
            "path": path,
        }

    def _load_existing_skills(self):
        """Load all previously learned skills from disk."""
        if not os.path.isdir(SKILLS_DIR):
            return
        count = 0
        for fname in os.listdir(SKILLS_DIR):
            if fname.endswith(".py"):
                name = fname[:-3]
                path = os.path.join(SKILLS_DIR, fname)
                try:
                    spec = importlib.util.spec_from_file_location(name, path)
                    module = importlib.util.module_from_spec(spec)
                    spec.loader.exec_module(module)
                    keywords = set(getattr(module, "SKILL_KEYWORDS", name.split("_")))
                    self.learned_skills[name] = {
                        "module": module,
                        "keywords": keywords,
                        "path": path,
                    }
                    count += 1
                except Exception as e:
                    logger.warning(f"Failed to load skill {name}: {e}")
        if count:
            logger.info(f"📦 Loaded {count} previously learned skills.")

    # ─── Execution ────────────────────────────────────────────────────────────

    def try_run_skill(self, user_input: str) -> Optional[str]:
        """Try to run a matching learned skill. Returns None if no match."""
        name = self._fuzzy_match_learned(user_input)
        if not name:
            return None
        skill = self.learned_skills[name]
        module = skill["module"]
        if hasattr(module, "run"):
            try:
                result = module.run(user_input)
                return result if isinstance(result, str) else str(result)
            except Exception as e:
                logger.error(f"Skill '{name}' runtime error: {e}")
                return f"The skill for '{name}' ran into an error: {e}"
        return None

    def list_skills(self) -> str:
        if not self.learned_skills:
            return "I haven't learned any new skills yet."
        names = [s.replace("_", " ") for s in self.learned_skills.keys()]
        return "Learned skills: " + ", ".join(names) + "."
